# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 18:37
from __future__ import unicode_literals

import core.apikeyauth.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=core.apikeyauth.utils.generate_token, max_length=100)),
                ('api_secret', models.CharField(default=core.apikeyauth.utils.generate_token, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
